spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411

eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: '*'  #打开全部请求端点*

feign:
  hystrix:
    enabled: true




