spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/tianyanmei/springcloudParent/ #master前面的参数
          searchPaths: com.zhouhj.springcloudConfig  #master后面的参数
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/